version: '3.9'
services:
  challenge:
    container_name: challenge
    environment:
      - DB_PASSWORD=qwerty
    tty: true
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/challenge
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - '5436:5432'